# This workflow will build a Java project with Maven on the daily basis (aka Nightly Build).
# Checks all supported environments.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  schedule:
  # Every day at 04:00 UTC
  - cron:  '0 4 * * *'
  # Manual run from the GitHub action page
  workflow_dispatch:
    inputs:
      mavenArgs:
        description: 'Maven goals and parameters'
        required: false
        default: '-DnoPerf'
      branch:
        description: 'Branch to build'
        required: false
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11, 16 ]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: ${{ matrix.os }}/java-${{ matrix.java }}

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout ${{ github.event.inputs.branch }}
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Set environment variables
      run: |
        echo "WEEK=$(date +%U)" >> $GITHUB_ENV
        echo "DAY=$(date +%w)" >> $GITHUB_ENV
      shell: bash

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-${{ env.WEEK }}-${{ env.DAY }}
        restore-keys: |
          maven-${{ env.WEEK }}
          maven-

    - name: Maven version
      run: mvn -v

    - name: Build with Maven
      run: mvn -B  ${{ github.event.inputs.mavenArgs }}
